# Generated by Django 6.0.4 on 2026-04-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_name', models.CharField(max_length=50)),
                ('g_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('g_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('g_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_type', models.CharField(max_length=2)),
                ('c_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dispatchers',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=50)),
                ('d_email', models.CharField(max_length=50, unique=True)),
                ('d_pass', models.CharField(max_length=99)),
            ],
            options={
                'db_table': 'dispatchers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('pk', models.CompositePrimaryKey('dr_id', 'l_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'driver_license',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('dr_id', models.AutoField(primary_key=True, serialize=False)),
                ('dr_name', models.CharField(max_length=50)),
                ('dr_tel', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'licenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_from', models.CharField(max_length=50)),
                ('r_to', models.CharField(max_length=50)),
                ('r_dist', models.IntegerField(blank=True, null=True)),
                ('r_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('tr_date_start', models.DateField()),
                ('tr_date_end', models.DateField(blank=True, null=True)),
                ('tr_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'shipments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transports',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_mark', models.CharField(max_length=30)),
                ('t_model', models.CharField(max_length=30)),
                ('t_number', models.CharField(max_length=15, unique=True)),
                ('t_cap', models.IntegerField()),
            ],
            options={
                'db_table': 'transports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('c', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.clients')),
                ('p_passp', models.CharField(max_length=50)),
                ('p_date', models.DateField(blank=True, null=True)),
                ('p_tel', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'individuals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegalEntities',
            fields=[
                ('c', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.clients')),
                ('y_inn', models.BigIntegerField(unique=True)),
                ('y_tel', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'legal_entities',
                'managed': False,
            },
        ),
    ]
